---
title: "Website Fun"
author: "Kelsey Griffin"
date: "October 17, 2018"
output: 
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: flatly
    
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Libraries
```{r}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
```

#loading the data

```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), 
                stringsAsFactors = FALSE)
```

#median by year

```{r}
escapement <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep="-") %>% 
  group_by(Species, Year) %>% 
  summarise(annualcount = sum(DailyCount)) %>% 
              group_by(Species) %>% 
              summarise(median_escapement = median(annualcount))
head(escapement)
```
#bar plot

Bar plot of median escapement by species.

```{r}
ggplot(escapement, aes(Species, median_escapement))+
  geom_col() +
  coord_flip()
```

#maps
## Clean the data
Remove columns we don't need, keep one row for each location.

```{r}
locations <- esc %>% 
  select(Location, Latitude, Longitude) %>% 
  group_by(Location, Latitude, Longitude) %>%
  summarise(n=n())%>%
  drop_na()

head(locations)
```

##Leaflet map

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup =~Location)
```

